### ISSUE TITLE
Add option to alternative MNI templates for output spaces

### ISSUE THREAD

**Issue by feilong** [poldracklab/smriprep#11]
From discussions of another issue (https://github.com/poldracklab/fmriprep/issues/337#issuecomment-297139529), it would be nice to have alternatives to `MNI152NLin2009cAsym` as output spaces to increase backward compatibility with other softwares, datasets, and atlases.  For example, currently widely used `MNI152NLin6Asym`.

I'll try to modify `fmriprep/workflows/anatomical.py` and add `output_spaces` as an input parameter to `init_anat_preproc_wf`, and change the spatial normalization code accordingly.  Does that sound good? @chrisfilo

**Comment by oesteban** [comment]
With #45 we are pretty close to getting this done. It would be really helpful if @effigies brought poldracklab/fmriprep#1115 from fmriprep. I can take the token from there. [That PR would also be helpful with lesion related issues]

**Comment by effigies** [comment]
@oesteban To be clear, that PR never worked on fMRIPrep, and I never had time to figure out why it didn't. If you think it will be helpful, I can try to get it to a similarly broken state against sMRIPrep `master`, but it's not obvious to me that it's worth the time.

**Comment by oesteban** [comment]
I see. Basically, I didn't want to throw your commits away. So, if you think that trying to bring that PR back will have more friction than just start over then I'm happy to take care of the issue.

**Comment by effigies** [comment]
I can see if it's fast. I'll try merging master on fMRIPrep, and if so, then I can just apply the diff in one shot over here.

**Comment by effigies** [comment]
I don't think this is plausibly addressable until we settle on niworkflows >= 0.6. There are currently too many moving parts with regard to these workflows, and trying to wedge this into pre-template-flow (or partial-template-flow? I don't actually know what the 0.5.x state is) code while also trying to move with post-template-flow is just asking for merge conflicts.

Now that we have 0.6, should we just get fMRIPrep/sMRIPrep to support it?

**Comment by oesteban** [comment]
I don't see any inconvenient other than the PR to niworkflows just referenced above to allow changing the `--template` target for smriprep (and fmriprep in the future). I'm just testing it out and I'm positive that it will work out.

A different issue is allowing several templates to be used as standard spaces. That will definitely require the implementation of something like poldracklab/fmriprep#1115.

**Comment by effigies** [comment]
Right, and poldracklab/fmriprep#1115 depends on poldracklab/niworkflows#236, which I've just rebased onto master, having to deal with template-flow changes in poldracklab/niworkflows#283.

It's not clear to me that rebasing poldracklab/niworkflows#283 onto `maint/0.5` in order to get poldracklab/fmriprep#1115 working with niworkflows 0.5.x is going to be a good use of time, when we're going to have to turn around and make everything compatible with niworkflows 0.6.

**Comment by oesteban** [comment]
> It's not clear to me that rebasing poldracklab/niworkflows#283 onto maint/0.5 in order to get poldracklab/fmriprep#1115 working with niworkflows 0.5.x is going to be a good use of time

Totally agree with this. I would work from master (i.e. niworkflows-0.6.x)
