### ISSUE TITLE
Gracefully handle pre-skull-stripped T1w images

### ISSUE THREAD

**Issue by effigies** [poldracklab/smriprep#12]
A number of subjects in ds000223 (e.g. [sub-07](https://s3.amazonaws.com/openneuro/ds000223/ds000223_R1.0.0/uncompressed/derivatives/mriqc/sub-07_T1w.html)) have pre-skull-stripped T1w images. ANTs skull-stripping on these datasets clips most superficial cortex, resulting in very poor preprocessing.

I propose adding a `--pre-skull-stripped` flag (or similar) to indicate that the anatomical workflow should assume the incoming image is already skull-stripped.

Alternately, we could do a test for a given percentage of zero voxels as evidence for skull-stripping, though this would need to be tested against defacers, as well.

**Comment by adelavega** [comment]
Yet another skulled stripped dataset on openneuro: https://openneuro.org/datasets/ds001132/versions/00002/file-display/sub-01:anat:sub-01_run-01_T1w.nii.gz

**Comment by effigies** [comment]
Related to [NeuroStars #4091](https://neurostars.org/t/4091), another thing we could consider is allowing users to supply their own `desc-brain_mask.nii.gz`, similar to how they currently supply lesion masks. In the existing dataset cases, we could simply filter T1w images with `T1w_data > 0` to produce a mask, that would then bypass the skullstripping workflow.

**Comment by tyarkoni** [comment]
This would increase the number of datasets we support in NeuroScout by at least 1, and possibly more, so if there's any way to prioritize this (especially given that it's tagged as low effort), it would be much appreciated.

**Comment by adelavega** [comment]
I tested out on a limited set of images (skullstripped, defaced, raw), Chris's suggestion of seeing if all extreme planes are all zeros. In my limited test case this worked.

I also looked into where I could stick this into the workflow. It seems like `niworkflows.anat.ants.init_brain_extraction_wf` is the right place.

I'm guessing, if this test indicates the image is skullstripped, we'd skip the ant normalization step, and potentially the following guassian interpolation, and thresholding. Instead, we could just threshold > 0 as @effigies suggested. 

Seem correct? This ants brain extraction workflow is a bit confusing as its not clear if "normalization" = "extraction"

**Comment by effigies** [comment]
Brain extraction and normalization are two different things. We would just skip extraction, and pass the skull stripped brain in two places for normalization.

**Comment by adelavega** [comment]
Makes sense, I just have no clue where the extraction happens then (is it `map_gaussian` with the templates? antsAI?), so if you could point me to which steps would be skipped, I'd be happy to give implementation a go and test w/ the datasets I have.

**Comment by effigies** [comment]
https://github.com/poldracklab/smriprep/blob/5b519b1e2446ec8b69848575d7bc67800474f035/smriprep/workflows/anatomical.py#L226-L231

https://github.com/poldracklab/smriprep/blob/5b519b1e2446ec8b69848575d7bc67800474f035/smriprep/workflows/anatomical.py#L259-L260

https://github.com/poldracklab/smriprep/blob/5b519b1e2446ec8b69848575d7bc67800474f035/smriprep/workflows/anatomical.py#L269-L270

I guess the question is whether to INU correct a skull-stripped image or assume that it already is. I think in the past we've assumed that a second application is generally not harmful, so as long as it doesn't depend on the presence of skull, it probably just makes sense to swap `brain_extraction_wf` with an N4 node.
