### ISSUE TITLE
Sphinxcontrib-versioning does not like changes in ``docs/config.py``

### ISSUE THREAD

**Issue by oesteban** [poldracklab/smriprep#147]
See https://app.circleci.com/jobs/github/poldracklab/smriprep/2059/parallel-runs/0/steps/0-108

/cc @rwblair

**Comment by rwblair** [comment]
I believe this is because the github link package is not listed in the docs requirements, and its code only exists on the branch in the PR. sphinx-versioning checks out other branches from the github remote and uses the PR branch's conf.py.

**Comment by oesteban** [comment]
Yup, that is what I thought. Shouldn't it just skip old branches because they are already generated?

**Comment by oesteban** [comment]
Ugh, I don't know whether it would fail with old tags, but I can see it is failing for master.

Should we not generate master in the build?

**Comment by oesteban** [comment]
It might be just as easy as using ``__file__`` as reference when adding the ``sphinxext`` folder to ``sys.path``.

**Comment by oesteban** [comment]
Fixed via c6371b5ffdb3cb7a7ded0a8935036597f0f3f60d

**Comment by rwblair** [comment]
I'm confused what was the path that ended up getting added with dirname as opposed to abspath?
