### ISSUE TITLE
aparc/aseg do not appear to be adjusted for any fsnative2t1w differences

### ISSUE THREAD

**Issue by effigies** [poldracklab/smriprep#154]
Looking through the aparc/aseg code, it appears that we assume the T1.mgz and T1w.nii.gz files are already in register:

https://github.com/poldracklab/smriprep/blob/a080cb946795bd77932217ab2392231126a57be0/smriprep/workflows/surfaces.py#L512-L541

I don't see anywhere else in the code where we account for differences when they are not.

**Comment by oesteban** [comment]
Isn't `Label2Vol` accounting for that? - as per the second example in https://surfer.nmr.mgh.harvard.edu/fswiki/FsAnat-to-NativeAnat

That's encoded with the `reg_header` input, right?

https://github.com/poldracklab/smriprep/blob/a080cb946795bd77932217ab2392231126a57be0/smriprep/workflows/surfaces.py#L536-L537

**Comment by oesteban** [comment]
Another reason/way to think about this is that the fsnative-t1w transform should only contain a translation (if any deviation from identity) when given in RAS2RAS.

It is not identity in VOX2VOX, because it is precisely trying to prescribe how the sampling translates between both data domains (original and conformed spaces).

**Comment by effigies** [comment]
I'm currently running sMRIPrep on ds000114 with the following approach:

```
recon-all -sd /data/out/ds000114-smriprep/freesurfer -s sub-01 \
    -i /data/bids/openneuro/ds000114/sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz \
    -i /data/bids/openneuro/ds000114/sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz \
    -autorecon1 -noskullstrip
smriprep-docker /data/bids/openneuro/ds000114 /data/out/ds000114-smriprep participant \
    --participant-label 01 -vv
```

FreeSurfer will create T1.mgz by aligning retest to test, fMRIPrep wil create T1w.nii.gz by aligning test to retest. This should create a non-identity `fsnative2t1w_xfm`, and allow us to verify whether there is an issue before attempting a fix, and a test bed for verifying a fix.

**Comment by oesteban** [comment]
Awesome, thanks for taking over - very much appreciated.

**Comment by effigies** [comment]
It looks like everything is completely shot if your T1w.nii.gz is out of alignment with your T1.mgz. Everything is aligned to T1.mgz, and not the fMRIPrep outputs. This is the brain mask:

![bad_mask](https://user-images.githubusercontent.com/83442/83933871-66287e80-a77a-11ea-8321-8d9be40e97a9.png)

**Comment by effigies** [comment]
The brain mask goes from good in the `brain_extraction_wf` to bad in `refine`, which takes its input from `aseg_to_native_wf.tonii`:

https://github.com/poldracklab/smriprep/blob/d8fe13da52690b7cf2edd71f6ec38c4d660bd405/smriprep/workflows/surfaces.py#L191

https://github.com/poldracklab/smriprep/blob/d8fe13da52690b7cf2edd71f6ec38c4d660bd405/smriprep/workflows/surfaces.py#L228-L238

So it should only be confined to this bit...

**Comment by effigies** [comment]
Also, good news: This bug shows up clearly in reports, so we shouldn't have hidden failures.
![bad_seg](https://user-images.githubusercontent.com/83442/83958744-5f197300-a843-11ea-9677-8edf8d08d980.png)
