### ISSUE TITLE
Dependency tracking

### ISSUE THREAD

**Issue by effigies** [poldracklab/smriprep#172]
This issue is intended to allow easy reference for the dependencies within the nipreps family of projects.

sMRIPrep requires niworkflows and generally must depend on one minor series of niworkflows for the duration of an sMRIPrep minor series. Each sMRIPrep series may also be depended on for an fMRIPrep series and/or a dMRIPrep series. Noting these dependencies here should make it easier to track when a new minor series needs to be created.

| sMRIPrep series | niworkflows series | | fMRIPrep series | dMRIPrep series |
|----|----|----|----|----|
| 0.6.x | `~= 1.2.0` | | 20.1.x | |
| 0.5.x | `~= 1.1.5` | | 20.0.x | |

xref poldracklab/fmriprep#2054

**Comment by oesteban** [comment]
Maybe we should add this table under the documentation for developers? That will make it easier to modify and review, rather than editing an issue - DYT?

**Comment by oesteban** [comment]
Or under www.nipreps.org, I'd be happy with that.

**Comment by effigies** [comment]
Those are fine, as long as it's easy to find. Pinned issues have worked fine for me in the past, but I'm not overly attached to them.

**Comment by oesteban** [comment]
The dependency matrix has been moved to https://www.nipreps.org/devs/versions/, to edit/suggest changes, please send a PR against the `mkdocs` branch (default) of https://github.com/nipreps/nipreps.github.io/blob/mkdocs/docs/devs/versions.md

This is part of the general strategy of setting up NiPreps as a community and platform for the development of these preprocessing BIDS-Apps.
