### ISSUE TITLE
Consider removing extra resampling

### ISSUE THREAD

**Issue by mgxd** [poldracklab/smriprep#195]
https://github.com/poldracklab/smriprep/blob/2ccfaaf582e0c948940e1505301942f89408460f/smriprep/workflows/surfaces.py#L518-L519

`tonative` should already produce a `nii.gz` file.

**Comment by oesteban** [comment]
I agree with this, but it won't fix poldracklab/fmriprep#2142 - the problematic file seems to be on standard space `'GLS005_ses-2_task-graphlocalizer_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz'`, meaning that it is resampled with `antsApplyTransforms` later in the stream.

**Comment by effigies** [comment]
Fixed in #201.
