### ISSUE TITLE
run label missing from `_from-orig_to-T1w_mode-image_xfm.txt`

### ISSUE THREAD

**Issue by fliem** [poldracklab/smriprep#199]
Related to #185  
Issue due to #188
 I have two T1w runs per session, but using `poldracklab/smriprep:0.6.0` the resulting xfm file lost the run label (hence, I only have one xfm per session: `smriprep/sub-{subject}/ses-{session}/anat/sub-{subject}_ses-{session}_from-orig_to-T1w_mode-image_xfm.txt`)

**Comment by effigies** [comment]
Good catch. I think all of our test cases have been 1 T1w per session.

Fixing this will fix incorrect derivatives while leaving working derivatives alone, so this can be done as a bug-fix.

**Comment by oesteban** [comment]
@fliem, would it be easy for you to test the new niworkflows branch? How do you usually run smriprep?

**Comment by fliem** [comment]
@oesteban I can confirm that this works as expected.
