### ISSUE TITLE
Make reusing freesurfer outputs more explicit

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/smriprep#27]
Reusing precomputed freesurfer outputs is currently supported, but requires a very specific approach that is often confusing for users. To make things more transparent I propose adding `--reuse-freesurfer-dir` flag pointing to a SUBJECTS_DIR which will be reused. When that flag is set recon-all should not be attempted.

**Comment by oesteban** [comment]
I guess the only missing bit here is to propagate the `--fs-subjects-dir` flag to fMRIPrep?

**Comment by effigies** [comment]
I think that's right.

**Comment by oesteban** [comment]
Opened a particular issue for this in fMRIPrep proper.
