### ISSUE TITLE
Using pre-run Freesurfer

### ISSUE THREAD

**Issue by araikes** [poldracklab/smriprep#4]
I recognize that this concept has been addressed in poldracklab/fmriprep#1182 and I have read that thread prior to posting here. I have previously posted here on this topic but I'll refresh it for the current error. I have the most current version of fmriprep (updated today).

I have run Freesurfer (BIDS/Freesurfer v 6.0) using a longitudinal pipeline for 29 participants. The output from that is currently in `OUTDIR/freesurfer`. I now am trying to fmriprep. I've run on a single subject in order to assess the usability of the prior freesurfer run. The process completed and I received the reports for the subject. However, none of the freesurfer derivatives are present. A careful inspection of the logs reveals that it finds the pre-run Freesurfer directory but doesn't utilize it.

Here is the error message:

> RuntimeError: Command:
> recon-all -autorecon1 -noskullstrip -openmp 4 -subjid sub-01 -sd /out/freesurfer -notalairach -nonuintensitycor -nonormalization
> Standard output:
> 
> ERROR: It appears that this subject ID is an existing
>        base/template from longitudinal processing (-base):
>        sub-01
>        If you are trying to re-run a -base template you
>        need to pass the -base and all -tp flags: 
> 
>        \' -base <templateid> -tp <tpNid> ... -all \'
> 
>        (Instead of -all you can pass other flags, such
>        as -autorecon2 -autorecon3 to run only parts.)
> Standard error:
> 
> Return code: 1

I am attaching the log file with the error. Here's the commands for fmriprep: 
```
docker run -i --rm \
-v $INDIVDIR:/data:ro \
-v $OUTDIR:/out \
-v /data/BL2/BIDS_derivatives/code/license.txt:/opt/freesurfer/license.txt \
poldracklab/fmriprep \
/data /out \
participant \
--longitudinal \
--low-mem \
--n_cpus 1 \
--output-space template T1w fsaverage \
--work-dir /scratch \
--use-aroma \
--participant_label "sub-$subject" \
--write-graph
```

Any help would be appreciated

[crash_log.txt](https://github.com/poldracklab/fmriprep/files/2215684/crash_log.txt)

**Comment by araikes** [comment]
@pettitta I'm just seeing this right now. I'm curious if this solution works for allowing FMRIPrep/Nipype to identify that Freesurfer has already been run and correctly import the expected folders?

**Comment by oesteban** [comment]
Was this ever addressed/documented? Thanks for your patience.

**Comment by oesteban** [comment]
I'll close this and welcome anyone who reopens it because it wasn't correctly addressed.

**Comment by effigies** [comment]
This isn't done, as it's about using longitudinal FreeSurfer. #21 should cover that.

**Comment by oesteban** [comment]
Let's then redirect everyone to the longitudinal FS issue you linked.
