### ISSUE TITLE
ERROR: talairach_afd: Talairach Transform: transforms/talairach.xfm ***FAILED*** (p=0.0455, pval=0.0034 < threshold=0.0050)

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/smriprep#5]
[A user reported issues with talairach transform in recon-all](https://neurostars.org/t/fmriprep-1-1-1-anat-only-troubleshooting-talairach-afd-error/2134/). The issue was resolved by performing rough coregistration of the input images before feeding them to freesurfer:

```
flirt -dof 6 -in OAS1_bids/sub-0180/anat/sub-0180_T1w.nii.gz -ref average_305.nii.gz -omat rigid.xfm -out OAS1_bids_sub-0180_fixed/sub-0180/anat/sub-0180_T1w.nii.gz
```

I wonder if we should build this into FMRIPREP - ideally the coregistration would be only saved in the headers so no additional interpolation would be performed.

**Comment by Lindadalaile** [comment]
Excuse me,I think I also get the same error for one of my subjects
Is there anyone me?I'm crazing
Here is the full detail. 
[error.txt](https://github.com/poldracklab/smriprep/files/3126444/error.txt)

**Comment by oesteban** [comment]
It doesn't look like an error. At least it doesn't look like this one:

```
$ grep "Talairach failed" error.txt
$
```

Please provide further details for us to help.

**Comment by Lindadalaile** [comment]
> It doesn't look like an error. At least it doesn't look like this one:
> 
> ```
> $ grep "Talairach failed" error.txt
> $
> ```
> 
> Please provide further details for us to help.

Thank you! I had solved this problem with others help. Thank you again.

**Comment by effigies** [comment]
Oh wait. This wasn't the originator...

**Comment by oesteban** [comment]
The original thread at neurostars appears as solved now. Even though we didn't directly address this, it seems the prevalence of this problem is low enough to close the issue. I also wonder how much FS7 has improved in this regard.

If anyone experiences this problem again, please reopen.
