### ISSUE TITLE
fmriprep-docker crashing during mri_robust_register

### ISSUE THREAD

**Issue by divyanganar** [poldracklab/smriprep#53]
Hi everyone!

Our team is trying to run fmriprep with just one subject as a test on the local machine and on the cluster to see how long it takes and have a look at the output and stuff. I'm facing different issues on the local machine and on the cluster. The version that I'm using is 1.2.6.

#### Local machine

I'm running:

```fmriprep-docker --fs-license-file /Users/divyangana/Desktop/license.txt --use-aroma /Users/divyangana/Desktop/Dicom_1sub/Dicom_1sub_BIDS /Users/divyangana/Desktop/Dicom_1sub/dicom_fmriprep_output```

Crash log:

[Crash_log.txt](https://github.com/poldracklab/fmriprep/files/2781532/Crash_log.txt)

This happened with a couple of different subjects. Any help would be great, thank you! Apologies if I'm doing something wrong, I'm quite new to this!

**Comment by divyanganar** [comment]
Memory was actually already at 32GB. I didn't really try very hard locally, because eventually we had to use the cluster (because of time). So ended up doing that! (#1478).

**Comment by oesteban** [comment]
I'll close for now. If you run into similar issues, please do not hesitate to open this back.
