### ISSUE TITLE
Rename anatomical outputs to conform to BIDS Derivatives RC1

### ISSUE THREAD

**Issue by effigies** [poldracklab/smriprep#6]
This is my interpretation of RC1. If it's incorrect, we may want to clarify the text.

@oesteban @satra @edickie Can you verify the transforms (bottom) and `space-` usage?
@ahoopes @edickie Can you verify the probseg/dseg/surfaces?

### Filenames

Using examples from ds114/sub-07/anat:

| Old | New |
|---|---|
| `sub-07_T1w_preproc.nii.gz` | <ul><li>[x] `sub-07_desc-preproc_T1w.nii.gz`</li></ul> |
| `sub-07_T1w_brainmask.nii.gz` | <ul><li>[x] `sub-07_desc-brain_mask.nii.gz`</li></ul> |
| `sub-07_T1w_class-{CSF\|GM\|WM}_probtissue.nii.gz` | <ul><li>[x] `sub-07_label-{CSF\|GM\|WM}_probseg.nii.gz`</li></ul> |
| `sub-07_T1w_dtissue.nii.gz` | <ul><li>[x] `sub-07_dseg.nii.gz`</li></ul> |
| `sub-07_T1w_[surftype].{L\|R}.surf.gii` | <ul><li>[x] `sub-07_hemi-{L\|R}_[surftype].surf.gii`</li></ul> |
| `sub-07_T1w_label-aparcaseg_roi.nii.gz` | <ul><li>[x] `sub-07_desc-aparcaseg_dseg.nii.gz`</li></ul> |
| `sub-07_T1w_label-aseg_roi.nii.gz` | <ul><li>[x] `sub-07_desc-aseg_dseg.nii.gz`</li></ul> |
| `sub-07_T1w_space-MNI152NLin2009cAsym_preproc.nii.gz` | <ul><li>[x] `sub-07_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz`</li></ul> |
| ... | ... |
| `sub-07_T1w_space-MNI152NLin2009cAsym_target-T1w_warp.h5` | <ul><li>[x] `sub-07_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5`</li></ul> |
| `sub-07_T1w_target-fsnative_affine.txt` | <ul><li>[x] `sub-07_from-T1w_to-fsnative_mode-image_xfm.txt`</li></ul> |
| `sub-07_T1w_target-MNI152NLin2009cAsym_warp.h5` | <ul><li>[x] `sub-07_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5`</li></ul> |

Additionally, we have multiple T1w images, so we have the following per-session files:

| Old | New |
|---|---|
| `sub-07_ses-<session>_T1w_space-orig_target-T1w_affine.txt` | <ul><li>[ ] `sub-07_ses-<session>_from-orig_to-T1w_mode-image_xfm.txt`</li></ul> |

### Metadata

- [x] T1w file must have `Space` and `SkullStripped` metadata
- [x] Brainmasks must have `RawSources`, `Space` and `Type` (`"Brain"`) metadata
- [x] dseg file should be checked to ensure tissue indices match section [7.4.3](https://docs.google.com/document/d/17ebopupQxuRwp7U7TFvS6BH03ALJOgGHufxK8ToAvyI/edit#heading=h.g35a71g5bvrk)
- [x] We should add a `dseg_labels.tsv` that matches `aparcaseg` and `aseg`. If it clashes with 7.4.3, we'll probably need to add a `desc-aseg` tag (and make a copy for `aparcaseg`).
- [ ] Transform files will need extensive metadata

**Comment by colinlaney** [comment]
I'm sorry, what is `xfm`? Looks like [FLIRT](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT/UserGuide) parameter, but doesn't make sense.

**Comment by effigies** [comment]
Transform.

**Comment by colinlaney** [comment]
Sure, but what kind of? I meant it was obviously: `affine` is linear transform, `warp` is non-linear transform. But `xfm` is not self-descriptive and it misleads to which transform we deal with. Only the file format suggests the type of transform now.

**Comment by effigies** [comment]
This is what is currently specified by the BIDS draft specification. See https://docs.google.com/document/d/17ebopupQxuRwp7U7TFvS6BH03ALJOgGHufxK8ToAvyI/edit#heading=h.rxc844jqesod

It does not appear to have made it into bids-standard/bids-specification#109, but it is currently what we have to work with.

**Comment by colinlaney** [comment]
Thank you, I have missed this update of BIDS.

**Comment by oesteban** [comment]
@ahoopes https://github.com/templateflow/tpl-fsaverage/blob/master/tpl-fsaverage_dseg.tsv - thanks!
