### ISSUE TITLE
Improve segmentation in cases of low tissue contrast

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/smriprep#7]
T1w scans of babies tend to have low tissue contrast causing poor segmentation. From a conversation with Cat C. I learned that SPM tends to perform slightly better than FSL, but [iBEAT](https://www.med.unc.edu/bric/ideagroup/free-softwares/libra-longitudinal-infant-brain-processing-package) works even better.

**Comment by oesteban** [comment]
Follow up on the new issue referenced above.
