### ISSUE TITLE
T1w workflow x-form inconsistency

### ISSUE THREAD

**Issue by oesteban** [poldracklab/smriprep#82]
DS000003's `anat_template_wf/t1_conform/mapflow/_t1_conform0/sub-11_T1w_ras.nii.gz` has the following headers:

```
descrip         : b'FreeSurfer Aug 11 2009'
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -79.0
qoffset_y       : -128.0
qoffset_z       : -128.0
srow_x          : [  1.   0.   0. -79.]
srow_y          : [   0.           1.3333334    0.        -128.       ]
srow_z          : [   0.           0.           1.3333334 -128.       ]
```

Given those q/s form codes, then the new version of antsBrainExtraction chokes because it includes a final refinement step using the WM mask in `N4BiasFieldCorrection`. The WM mask calculated by atropos has different headers:

```
descrip         : b''
aux_file        : b''
qform_code      : aligned
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -79.0
qoffset_y       : -127.99999
qoffset_z       : -127.99999
srow_x          : [  1.   0.  -0. -79.]
srow_y          : [   0.           1.3333334   -0.        -127.99999  ]
srow_z          : [   0.           0.           1.3333334 -127.99999  ]
```

The proposal would be double:
1. Include a validation node after the T1w template has been computed that ensure x-forms are sane (same heuristics as in BOLD images).
2. Update the antsBrainExtraction workflow to copy headers to all reused results (bias corrected, bias field, brain mask, and wm mask).

**Comment by oesteban** [comment]
@effigies any ideas against point 1 of the proposed fix?

**Comment by effigies** [comment]
Nope, that seems reasonable.
