### ISSUE TITLE
MAINT: Change installation to ``setup.cfg`` for pip > 19

### ISSUE THREAD

**Issue by oesteban** [poldracklab/smriprep#95]
Comes from #93

**Comment by effigies** [comment]
Should set a minimum setuptools of 30.3.0 in `setup_requires` and `pyproject.toml`. This should get us into a place where having a recent pip OR a recent setuptools will install correctly, and an understandable error will be printed if neither is new enough.

There was a little discussion on nipy/nibabel#764. See the full comparison (https://github.com/nipy/nibabel/compare/935079b45d9d9477c2b59993a91edf2c3890336a...0282bb957f990100aaf39d19bd3e9c7606b4fe6d) for all modifications.
